[package]
name = "goodtype-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
goodtype-core = { path = "../../../crates/goodtype-core" }
goodtype-typst = { path = "../../../crates/goodtype-typst" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
tempfile.workspace = true
